### ISSUE TITLE
readme how to update the build

### ISSUE THREAD

**Issue by noxonsu** [noxonsu/definance#3]
добавить инфу как обновлять билд

**Comment by Disti4ct** [comment]
сейчас увидел что также должен изменяться `definance_main.php`. В моем случае это [место с названием js чанков](https://github.com/noxonsu/definance/blob/1352216d31f8ff5b346ede9c0dcab9abe2c5b3de/templates/definance_main.php?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L143). Возможно надо обновлять что то еще в файле, просто сейчас только номер чанков сменился. В итоге надо что-то придумать для авто обновления или нам надоест это в ручную делать ).

- [в том же месте](https://github.com/noxonsu/definance/blob/1352216d31f8ff5b346ede9c0dcab9abe2c5b3de/templates/definance_main.php?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L143) мы указываем `vendor_cache` директорию, но она пустая
- этот стиль из пакета `@reach/dialog`. Используется в `components/Modal/index.tsx`: https://github.com/noxonsu/definance/blob/1352216d31f8ff5b346ede9c0dcab9abe2c5b3de/templates/definance_main.php#L119

**Comment by shendel** [comment]
> сейчас увидел что также должен изменяться `definance_main.php`. В моем случае это [место с названием js чанков](https://github.com/noxonsu/definance/blob/1352216d31f8ff5b346ede9c0dcab9abe2c5b3de/templates/definance_main.php?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L143). Возможно надо обновлять что то еще в файле, просто сейчас только номер чанков сменился. В итоге надо что-то придумать для авто обновления или нам надоест это в ручную делать ).
> 
> * [в том же месте](https://github.com/noxonsu/definance/blob/1352216d31f8ff5b346ede9c0dcab9abe2c5b3de/templates/definance_main.php?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L143) мы указываем `vendor_cache` директорию, но она пустая
> * этот стиль из пакета `@reach/dialog`. Используется в `components/Modal/index.tsx`: https://github.com/noxonsu/definance/blob/1352216d31f8ff5b346ede9c0dcab9abe2c5b3de/templates/definance_main.php#L119

у тебя в билде ```npm run build_clean``` - там убран шех чанков. по сути только номер версии менять в ``` definance_main.php ```
папка ```vendor_cache``` и должна быть пустая. при запуске вызывает ``` definance_prepare_vendor```  , где 1. Берется вендор из ``` vendor_source```, 2. Исправляет пути к файлам 3. Ложит исправленые js в папку кеша
Подключает уже из кеша
В рабочем режиме ```vendor_cache``` выглядит так 
![image](https://user-images.githubusercontent.com/1880211/151231326-8a267d9c-580d-413c-9089-19130c99e455.png)
Внутри уже поправленные js файлы
![image](https://user-images.githubusercontent.com/1880211/151231411-1c1edcc0-824c-4c17-b793-910c8b34a333.png)

Для обновления вендора - тебе нужно сделать 
1. ```npm run build_clean```
2.  скопировать содержимое твоей папки ```build``` в папку ```vendor_source``` WP плагина (удалив содержимое)
3. Увеличить версию в ```definance_main.php```

Из всего вышесказанного следует, что мы можем только устать менять версию в главном файле (тема актуальная) - можно разработать универсальный скрипт, и использовать его на всех плагинах. В том-же кошельке есть обновление автоматом, но оно тоже немного кривое
Со стилями ```этот стиль из пакета @reach/dialog. Используется в components/Modal/index.tsx``` надо проработать

**Comment by Disti4ct** [comment]
> по сути только номер версии менять в definance_main.php
* менять в `definance.php`

я говорю про номера чанков в `definance_main.php`:
![image](https://user-images.githubusercontent.com/61930014/151302713-6f660df7-9930-4b02-920b-c573e474dae8.png)

сначало было `2.chunk.js`, в одной из обнов стало `3.chunk.js`

**Comment by shendel** [comment]
> > по сути только номер версии менять в definance_main.php
> 
> * менять в `definance.php`
> 
> я говорю про номера чанков в `definance_main.php`: ![image](https://user-images.githubusercontent.com/61930014/151302713-6f660df7-9930-4b02-920b-c573e474dae8.png)
> 
> сначало было `2.chunk.js`, в одной из обнов стало `3.chunk.js`

да, надо подумать над этим

**Comment by VitaliyShulik** [comment]
looks like solved
