### ISSUE TITLE
Wallet connect BSC error

### ISSUE THREAD

**Issue by noxonsu** [noxonsu/definance#30]
![](https://screenshots.wpmix.net/chrome_lPaN2Z1dNKT5EE2KrousbYaVtAWnleQy.png)

хочу зайти с wallet connect получаю это

**Comment by Disti4ct** [comment]
не связано с сетью. В логах статус 404. Как будто опять проблема с подключением файлов сборки

**Comment by noxonsu** [comment]
![](https://screenshots.wpmix.net/chrome_DkxgJAkniYMYD8uBl9N98KjbIVJhcTRE.png) 

он пытается подключить файлы с корня, а надо относительно. вроду у mcw такая ж проблема был и сделали вот эту штуку https://screenshots.wpmix.net/chrome_x4CWij8jo8dK64m37BFFFim9YtCzA5q6.png

**Comment by Disti4ct** [comment]
https://github.com/noxonsu/definance/pull/36/commits/9b223907ff5e061b30d88ddcd49ea34c20477942

**Comment by VitaliyShulik** [comment]
Looks like solved
